---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: ENV
          value: "staging"
        - name: GPU_ENABLED
          value: "1"
        - name: TEST
          value: "true"
      
